import { PlayerWithStats } from '../types/player';
import { Chat } from '../types/chat';
import { RankingEntry } from '../types/stats';
import { Competition } from '../types/stats';

export const DUMMY_MBAPPE: PlayerWithStats = {
  id: 278,
  name: 'Kylian Mbappé',
  firstname: 'Kylian',
  lastname: 'Mbappé',
  age: 27,
  nationality: 'Frankreich',
  nationalityFlag: '🇫🇷',
  height: '1,78',
  preferredFoot: 'Rechts',
  photo: 'https://media.api-sports.io/football/players/278.png',
  position: 'ST',
  team: {
    id: 541,
    name: 'Real Madrid',
    logo: 'https://media.api-sports.io/football/teams/541.png',
  },
  number: 9,
  stats: {
    goals: 30,
    assists: 7,
    xG: 28,
    xA: 6,
    shots: 95,
    shotsOnTarget: 52,
    dribbles: 89,
    dribbleSuccessRate: 56.4,
    passes: 412,
    passSuccessRate: 78.2,
    chancesCreated: 34,
    bigChancesCreated: 12,
    tackles: 18,
    tackleSuccessRate: 55,
    interceptions: 8,
    clearances: 2,
    appearances: 25,
    rating: 7.9,
  },
};

export const DUMMY_KANE: PlayerWithStats = {
  id: 184,
  name: 'Harry Kane',
  firstname: 'Harry',
  lastname: 'Kane',
  age: 32,
  nationality: 'England',
  nationalityFlag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  height: '1,88',
  preferredFoot: 'Rechts',
  photo: 'https://media.api-sports.io/football/players/184.png',
  position: 'ST',
  team: {
    id: 157,
    name: 'Bayern München',
    logo: 'https://media.api-sports.io/football/teams/157.png',
  },
  number: 9,
  stats: {
    goals: 24,
    assists: 9,
    xG: 22,
    xA: 8,
    shots: 78,
    shotsOnTarget: 41,
    dribbles: 34,
    dribbleSuccessRate: 41.2,
    passes: 634,
    passSuccessRate: 82.5,
    chancesCreated: 41,
    bigChancesCreated: 15,
    tackles: 12,
    tackleSuccessRate: 50,
    interceptions: 5,
    clearances: 3,
    appearances: 23,
    rating: 7.6,
  },
};

export const DUMMY_VINICIUS: PlayerWithStats = {
  id: 1094,
  name: 'Vinícius Jr.',
  firstname: 'Vinícius',
  lastname: 'Júnior',
  age: 25,
  nationality: 'Brasilien',
  nationalityFlag: '🇧🇷',
  height: '1,76',
  preferredFoot: 'Rechts',
  photo: 'https://media.api-sports.io/football/players/1094.png',
  position: 'LF',
  team: {
    id: 541,
    name: 'Real Madrid',
    logo: 'https://media.api-sports.io/football/teams/541.png',
  },
  number: 7,
  stats: {
    goals: 18,
    assists: 11,
    xG: 15,
    xA: 10,
    shots: 72,
    shotsOnTarget: 38,
    dribbles: 134,
    dribbleSuccessRate: 62.7,
    passes: 523,
    passSuccessRate: 74.8,
    chancesCreated: 52,
    bigChancesCreated: 18,
    tackles: 22,
    tackleSuccessRate: 48,
    interceptions: 12,
    clearances: 4,
    appearances: 24,
    rating: 7.8,
  },
};

export const DUMMY_CHATS: Chat[] = [
  {
    id: '1',
    title: 'Meisten Tore in 2026',
    messages: [],
    createdAt: new Date('2026-03-10'),
    updatedAt: new Date('2026-03-10'),
  },
  {
    id: '2',
    title: 'Vinicius vs Olise in 25/26',
    messages: [],
    createdAt: new Date('2026-03-12'),
    updatedAt: new Date('2026-03-12'),
  },
  {
    id: '3',
    title: 'Ronaldo vs Messi All Time',
    messages: [],
    createdAt: new Date('2026-03-15'),
    updatedAt: new Date('2026-03-15'),
  },
];

export const DUMMY_RANKINGS_ST: Array<PlayerWithStats & { rank: number; score: number }> = [
  { ...DUMMY_MBAPPE, rank: 1, score: 152 },
  { ...DUMMY_KANE, rank: 2, score: 118 },
  {
    ...DUMMY_VINICIUS,
    rank: 3,
    score: 109,
    position: 'ST',
    name: 'Erling Haaland',
    firstname: 'Erling',
    lastname: 'Haaland',
    age: 26,
    nationality: 'Norwegen',
    nationalityFlag: '🇳🇴',
    number: 9,
    team: { id: 50, name: 'Manchester City', logo: 'https://media.api-sports.io/football/teams/50.png' },
    stats: { ...DUMMY_VINICIUS.stats, goals: 27, assists: 5, rating: 7.7 },
  },
  {
    ...DUMMY_KANE,
    rank: 4,
    score: 98,
    id: 521,
    name: 'Lautaro Martínez',
    firstname: 'Lautaro',
    lastname: 'Martínez',
    age: 28,
    nationality: 'Argentinien',
    nationalityFlag: '🇦🇷',
    number: 10,
    team: { id: 505, name: 'Inter Mailand', logo: 'https://media.api-sports.io/football/teams/505.png' },
    stats: { ...DUMMY_KANE.stats, goals: 20, assists: 6, rating: 7.4 },
  },
  {
    ...DUMMY_KANE,
    rank: 5,
    score: 91,
    id: 306,
    name: 'Viktor Gyökeres',
    firstname: 'Viktor',
    lastname: 'Gyökeres',
    age: 27,
    nationality: 'Schweden',
    nationalityFlag: '🇸🇪',
    number: 9,
    team: { id: 228, name: 'Sporting CP', logo: 'https://media.api-sports.io/football/teams/228.png' },
    stats: { ...DUMMY_KANE.stats, goals: 22, assists: 4, rating: 7.5 },
  },
];

export const DUMMY_COMPETITIONS: Competition[] = [
  { id: 140, name: 'LaLiga', logo: 'https://media.api-sports.io/football/leagues/140.png', season: '25/26' },
  { id: 2, name: 'UEFA Champions League', logo: 'https://media.api-sports.io/football/leagues/2.png', season: '25/26' },
  { id: 143, name: 'Copa del Rey', logo: 'https://media.api-sports.io/football/leagues/143.png', season: '25/26' },
  { id: 556, name: 'Supercopa', logo: 'https://media.api-sports.io/football/leagues/556.png', season: '25/26' },
];

export const DUMMY_SEARCH_PLAYERS = [DUMMY_MBAPPE, DUMMY_KANE, DUMMY_VINICIUS];
